version: '3'

services:
  postgres:
    image: postgres
    user: ${LISTCONTROLS_UID}
    environment: # Set up postgres database name and password
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: open_drugs
      POSTGRES_USER: admin
    ports: # Set up ports exposed for other containers to connect to
      - 5433:5432
    networks:
      - postgres_net
    volumes:
      - ./../listcontrols-postgres:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

  api:
    user: ${LISTCONTROLS_UID}
    build:
      context: api/
      dockerfile: Dockerfile
    image: listcontrols-backend-dev
    hostname: listcontrols-api
    container_name: listcontrols-api-dev
    volumes:
      - "./api:/api"
      - "./api/.env:/.env"
      - "./api/requirements.txt:/requirements.txt"
    depends_on:
      - postgres
    networks:
      - postgres_net

  cms:
    user: ${LISTCONTROLS_UID}
    build:
      context: cms/
      dockerfile: Dockerfile
    image: listcontrols-cms-dev
    hostname: listcontrols-cms
    container_name: listcontrols--cms-dev
    volumes:
      - "./cms:/cms"
      - "./cms/.env:/.env"
      - "./cms/requirements.txt:/requirements.txt"
    depends_on:
      - postgres
    networks:
      - postgres_net

networks:
  postgres_net:
    external:
      name: postgres_net
  default:
    external: false

